# General Params
verbosity: 3
global_frame_name: world
sensor_frame_name: airsim_drone/Depth_cam
label_path: /home/lukas/Documents/Datasets/flat_dataset/detectron_labels.csv
change_detection_interval: 0.0
visualization_interval: -1.0
data_logging_interval: -1.0
max_input_queue_length: 100

camera:
  verbosity: 0
  width: 640  # Px
  height: 480
  vx: 320
  vy: 240
  fx: 320
  fy: 320
  max_range: 5  # m
  min_range: 0.1

id_tracker:
  type: single_tsdf  # single_tsdf, ground_truth, projective, detectron
  verbosity: 1
  voxel_size: 0.2
  voxels_per_side: 16
  truncation_distance: -2 # negative = #vs
  
tsdf_integrator:  
  type: single_tsdf # projective, class_projective, single_tsdf
  verbosity: 1
  use_weight_dropoff: true
  max_weight: 10000
  interpolation_method: bilinear  # nearest, bilinear, adaptive
  foreign_rays_clear: false
  integration_threads: 1
  
visualization:
  verbosity: 1
  
  # Submaps
  color_mode: color # submaps, instances, color, normals, classes, change, classification
  visualization_mode: active  # all, active, active_only
  submap_color_discretization: 20
  visualize_mesh: true
  visualize_tsdf_blocks: true
  visualize_free_space: true
  visualize_bounding_volumes: true
  include_free_space: false
  mesh_min_weight: 0.000001
  
  # Planning
  visualize_slice: true
  planning_slice_resolution: 0.1
  planning_slice_height: -0.5
  
  # Tracking
  visualize_tracking: true
  
data_writer:
  verbosity: 1
  output_directory: /home/lukas/Documents/PanopticMapping/Data/run_logs
  file_name: ""

  

