# General Params
verbosity: 3
global_frame_name: world
label_path: /home/lukas/Documents/datasets/flat_dataset/labels.csv
change_detection_interval: -1.0
visualization_interval: -1.0

tsdf_integrator:  
  type: projective # naive, projective
  verbosity: 1
  
  # projective args
  width: 640
  height: 480
  vx: 320
  vy: 240
  fx: 320
  fy: 320
  max_range: 5  # m
  min_range: 0.1
  
  use_weight_dropoff: true
  sparsity_compensation_factor: 1.0
  max_weight: 10000
  interpolation_method: bilinear  # nearest, bilinear, adaptive, semantic
  foreign_rays_clear: true
  
  # naive args
  voxblox_integrator_type: fast # projective, fast
  sensor_vertical_field_of_view_degrees: 73.7397952
  use_const_weight: true  
  max_ray_length_m: 5
  voxel_carving_enabled: true
  use_weight_dropoff: true
  sparsity_compensation_factor: 1.0

#  truncation_distance: 0.2
#  max_ray_length_m: 5.0
#  use_const_weight: false
#  use_sparsity_compensation_factor: true
#  sparsity_compensation_factor: 20.0
#  integration_order_mode: "sorted"

id_tracker:
  type: detectron # ground_truth, detectron
  verbosity: 4
  instance_voxel_size: 0.03
  background_voxel_size: 0.08
  unknown_voxel_size: 0.08
  freespace_voxel_size: 0.3
  voxels_per_side: 16
  
  # Detectron ID tracker (TODO clean up)
  width: 640
  height: 480
  vx: 320
  vy: 240
  fx: 320
  fy: 320
  max_range: 5  # m
  min_range: 0.1
  paint_by_id: true
  track_against_map: true
  
tsdf_registrator:
  verbosity: 1
  min_voxel_weight: 0.000001
  error_threshold: -2 # m, negative = #voxel_sizes
  match_rejection_points: 50
  match_rejection_percentage: 0.1
  match_acceptance_points: 50
  match_acceptance_percentage: 0.1
  normalize_by_voxel_weight: true
  
visualization:
  verbosity: 1
  
  # Submaps
  color_mode: submaps # submaps, instances, color, normals, classes, change
  visualization_mode: active  # all, active 
  submap_color_discretization: 50
  visualize_mesh: true
  visualize_tsdf_blocks: true
  visualize_free_space: true
  visualize_bounding_volumes: true
  include_free_space: true
  mesh_min_weight: 0.000001
  
  # Planning
  visualize_slice: true
  planning_slice_resolution: 0.1
  planning_slice_height: -0.5


  

